name: ForzaLiveMap
services:
  Database:
    container_name: Database
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretVeryStrongPassword123!
      POSTGRES_DB: LiveMap
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - forzalivetelemetry

  API:
    container_name: API
    depends_on:
      Database:
        condition: service_started
        restart: false
    build:
      context: ../
      dockerfile: DevOps/Dockerfile
    ports:
      - 32700:8080
      - 5690:5690/udp
    networks:
      - forzalivetelemetry

networks:
  forzalivetelemetry:

volumes:
  db_data: